on:
  release:
    types: [created]

name: Publish to crate

jobs:
  publish:
    name: Publish to cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"

      - uses: jetli/trunk-action@v0.1.0
        with:
          # Optional version of trunk to install(eg. 'v0.8.1', 'latest')
          version: 'latest'

      - run: cargo test

      - run: rustup target add wasm32-unknown-unknown && trunk build
        working-directory: demo_respo/

      - uses: katyo/publish-crates@v1
        with:
          path: respo/
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
